checking cvs and compile return results

diff --git a/tools/cooja/contiki_tests/RUN_ALL b/tools/cooja/contiki_tests/RUN_ALL
--- a/tools/cooja/contiki_tests/RUN_ALL
+++ b/tools/cooja/contiki_tests/RUN_ALL
@@ -10,6 +10,12 @@ if [ -z "$MAILTO" ]; then
   exit
 fi
 
+function mail_report {
+  echo ">>>>>>> Sending mail <<<<<<<<"
+  cp $LOG ~/lastlog.log
+  cat $LOG | mail -s "Contiki test results" $MAILTO
+}
+
 echo ">>>>>>> Cleaning up previous tests <<<<<<<<"
 rm -f *.log *.cooja_log
 rm -fr se obj_cooja
@@ -24,14 +30,25 @@ echo "Test run started at `date '+%F %T'`" >> $LOG
 echo "" >> $LOG
 
 echo ">>>>>>> Updating from CVS <<<<<<<<"
-echo "Updating anonymous Sourceforge CVS" >> $LOG
+echo -n "Updating CVS: " >> $LOG
 (cd $CONTIKI && cvs update -dP)
+if [ "$?" != "0" ]; then
+  echo "FAIL" >> $LOG
+  mail_report
+  exit
+fi
+echo "OK" >> $LOG
 
 echo ">>>>>>> Building COOJA <<<<<<<<"
-echo "Building COOJA" >> $LOG
+echo -n "Building COOJA: " >> $LOG
 (cd $CONTIKI/tools/cooja && ant clean && ant jar)
+if [ "$?" != "0" ]; then
+  echo "FAIL" >> $LOG
+  mail_report
+  exit
+fi
+echo "OK" >> $LOG
 
-echo "Starting tests" >> $LOG
 echo "" >> $LOG
 for myfile in ./*.csc
 do
@@ -40,7 +57,4 @@ do
   echo "" >> $LOG   
 done
 
-echo ">>>>>>> Sending mail <<<<<<<<"
-echo "Mailing test report" >> $LOG
-cp $LOG ~/lastlog.log
-cat $LOG | mail -s "Contiki test results" $MAILTO
+mail_report
